# Compiler
CC = g++

EXE = solar_system

SOURCES = main.cpp

CXXFLAGS = -g -Wall -Wformat -std=c++11 -Wno-misleading-indentation

LIBS= -lglfw -lOpenGL

all:
	$(CC) $(CXXFLAGS) $(SOURCES) -o $(EXE) $(LFLAGS) $(LIBS)

clean:
	rm $(EXE)
